const BACKGROUND_TASK_TYPE_CALENDAR_SYNC = 'calendar_sync';
const BACKGROUND_TASK_TYPE_ACTION_STATUS_SYNC = 'action_status_sync';
const BACKGROUND_TASK_TYPE_IMAP_POLLING = 'imap_polling';
const BACKGROUND_TASK_TYPE_SCHEDULED_DIGEST = 'scheduled_digest';
const BACKGROUND_TASK_TYPE_OAUTH2_REFRESH = 'oauth2_refresh';
const BACKGROUND_TASK_TYPE_SCHEDULED_ACTION_EXECUTION = 'scheduled_action_execution';
const BACKGROUND_TASK_TYPE_GOOGLE_DRIVE_SYNC = 'google_drive_sync';
const BACKGROUND_TASK_TYPE_ONEDRIVE_SYNC = 'onedrive_sync';

export {
  BACKGROUND_TASK_TYPE_CALENDAR_SYNC,
  BACKGROUND_TASK_TYPE_ACTION_STATUS_SYNC,
  BACKGROUND_TASK_TYPE_IMAP_POLLING,
  BACKGROUND_TASK_TYPE_SCHEDULED_DIGEST,
  BACKGROUND_TASK_TYPE_OAUTH2_REFRESH,
  BACKGROUND_TASK_TYPE_SCHEDULED_ACTION_EXECUTION,
  BACKGROUND_TASK_TYPE_GOOGLE_DRIVE_SYNC,
  BACKGROUND_TASK_TYPE_ONEDRIVE_SYNC,
};
