const BACKGROUND_TASK_TYPE_CALENDAR_SYNC = 'calendar_sync';
const BACKGROUND_TASK_TYPE_ACTION_STATUS_SYNC = 'action_status_sync';
const BACKGROUND_TASK_TYPE_IMAP_POLLING = 'imap_polling';
const BACKGROUND_TASK_TYPE_SCHEDULED_DIGEST = 'scheduled_digest';
const BACKGROUND_TASK_TYPE_OAUTH2_REFRESH = 'oauth2_refresh';

export {
  BACKGROUND_TASK_TYPE_CALENDAR_SYNC,
  BACKGROUND_TASK_TYPE_ACTION_STATUS_SYNC,
  BACKGROUND_TASK_TYPE_IMAP_POLLING,
  BACKGROUND_TASK_TYPE_SCHEDULED_DIGEST,
  BACKGROUND_TASK_TYPE_OAUTH2_REFRESH,
};
