const DEFAULT_MAX_APPLICATIONS_PER_USER = '99';
const DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES = '15';
const DEFAULT_GMAIL_WATCH_RENEWAL_WINDOW_HOURS = '48';
const DEFAULT_OUTLOOK_SUBSCRIPTION_RENEWAL_WINDOW_HOURS = '24';
const DEFAULT_OUTLOOK_SUBSCRIPTION_TTL_DAYS = '6';
const DEFAULT_EMAIL_SUMMARY_MODEL = '@cf/meta/llama-3.1-8b-instruct';
const DEFAULT_MAX_EMAIL_BODY_CHARS = '12000';
const DEFAULT_AI_EMBEDDING_MODEL = '@cf/baai/bge-base-en-v1.5';
const DEFAULT_RAG_TOP_K = '5';
const DEFAULT_RAG_VECTOR_QUERY_TOP_K = '50';
const DEFAULT_MAX_CONTEXT_MEMORY_CHARS = '1800';
const DEFAULT_MAX_RAG_CONTEXT_CHARS = '6000';

export {
  DEFAULT_AI_EMBEDDING_MODEL,
  DEFAULT_EMAIL_SUMMARY_MODEL,
  DEFAULT_GMAIL_WATCH_RENEWAL_WINDOW_HOURS,
  DEFAULT_MAX_CONTEXT_MEMORY_CHARS,
  DEFAULT_MAX_EMAIL_BODY_CHARS,
  DEFAULT_MAX_RAG_CONTEXT_CHARS,
  DEFAULT_MAX_APPLICATIONS_PER_USER,
  DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES,
  DEFAULT_OUTLOOK_SUBSCRIPTION_RENEWAL_WINDOW_HOURS,
  DEFAULT_OUTLOOK_SUBSCRIPTION_TTL_DAYS,
  DEFAULT_RAG_TOP_K,
  DEFAULT_RAG_VECTOR_QUERY_TOP_K,
};
