const APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE = 'active';
const APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED = 'deleted';
const APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR = 'error';

const APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED = 'accepted';
const APPLICATION_CONTEXT_DELETION_STATUS_ERROR = 'error';

type ApplicationContextDocumentStatus =
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR;

type ApplicationContextDeletionStatus =
  | typeof APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED
  | typeof APPLICATION_CONTEXT_DELETION_STATUS_ERROR;

const CONTEXT_AUDIT_EVENT_EMAIL_RECEIVED = 'email_received';
const CONTEXT_AUDIT_EVENT_PROCESSING_STARTED = 'processing_started';
const CONTEXT_AUDIT_EVENT_CONTEXT_INDEXED = 'context_indexed';
const CONTEXT_AUDIT_EVENT_CONTEXT_SKIPPED = 'context_skipped';
const CONTEXT_AUDIT_EVENT_EMBEDDING_GENERATED = 'embedding_generated';
const CONTEXT_AUDIT_EVENT_MODEL_FALLBACK = 'model_fallback';
const CONTEXT_AUDIT_EVENT_RAG_QUERIED = 'rag_queried';
const CONTEXT_AUDIT_EVENT_SUMMARY_GENERATED = 'summary_generated';
const CONTEXT_AUDIT_EVENT_ACTION_CREATED = 'action_created';
const CONTEXT_AUDIT_EVENT_ACTION_EXECUTED = 'action_executed';
const CONTEXT_AUDIT_EVENT_DOCUMENT_DELETED = 'document_deleted';
const CONTEXT_AUDIT_EVENT_SUMMARY_SENT = 'summary_sent';
const CONTEXT_AUDIT_EVENT_ERROR = 'error';

const CONTEXT_AUDIT_LOG_SEVERITY_INFO = 'info';
const CONTEXT_AUDIT_LOG_SEVERITY_WARNING = 'warning';
const CONTEXT_AUDIT_LOG_SEVERITY_ERROR = 'error';

type ContextAuditEventType =
  | typeof CONTEXT_AUDIT_EVENT_EMAIL_RECEIVED
  | typeof CONTEXT_AUDIT_EVENT_PROCESSING_STARTED
  | typeof CONTEXT_AUDIT_EVENT_CONTEXT_INDEXED
  | typeof CONTEXT_AUDIT_EVENT_CONTEXT_SKIPPED
  | typeof CONTEXT_AUDIT_EVENT_EMBEDDING_GENERATED
  | typeof CONTEXT_AUDIT_EVENT_MODEL_FALLBACK
  | typeof CONTEXT_AUDIT_EVENT_RAG_QUERIED
  | typeof CONTEXT_AUDIT_EVENT_SUMMARY_GENERATED
  | typeof CONTEXT_AUDIT_EVENT_ACTION_CREATED
  | typeof CONTEXT_AUDIT_EVENT_ACTION_EXECUTED
  | typeof CONTEXT_AUDIT_EVENT_DOCUMENT_DELETED
  | typeof CONTEXT_AUDIT_EVENT_SUMMARY_SENT
  | typeof CONTEXT_AUDIT_EVENT_ERROR;

type ContextAuditLogSeverity =
  | typeof CONTEXT_AUDIT_LOG_SEVERITY_INFO
  | typeof CONTEXT_AUDIT_LOG_SEVERITY_WARNING
  | typeof CONTEXT_AUDIT_LOG_SEVERITY_ERROR;

export {
  APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED,
  APPLICATION_CONTEXT_DELETION_STATUS_ERROR,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR,
  CONTEXT_AUDIT_EVENT_EMAIL_RECEIVED,
  CONTEXT_AUDIT_EVENT_PROCESSING_STARTED,
  CONTEXT_AUDIT_EVENT_CONTEXT_INDEXED,
  CONTEXT_AUDIT_EVENT_CONTEXT_SKIPPED,
  CONTEXT_AUDIT_EVENT_EMBEDDING_GENERATED,
  CONTEXT_AUDIT_EVENT_MODEL_FALLBACK,
  CONTEXT_AUDIT_EVENT_RAG_QUERIED,
  CONTEXT_AUDIT_EVENT_SUMMARY_GENERATED,
  CONTEXT_AUDIT_EVENT_ACTION_CREATED,
  CONTEXT_AUDIT_EVENT_ACTION_EXECUTED,
  CONTEXT_AUDIT_EVENT_DOCUMENT_DELETED,
  CONTEXT_AUDIT_EVENT_SUMMARY_SENT,
  CONTEXT_AUDIT_EVENT_ERROR,
  CONTEXT_AUDIT_LOG_SEVERITY_INFO,
  CONTEXT_AUDIT_LOG_SEVERITY_WARNING,
  CONTEXT_AUDIT_LOG_SEVERITY_ERROR,
};
export type { ApplicationContextDeletionStatus, ApplicationContextDocumentStatus, ContextAuditEventType, ContextAuditLogSeverity };
