const APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE = 'active';
const APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED = 'deleted';
const APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR = 'error';

const APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED = 'accepted';
const APPLICATION_CONTEXT_DELETION_STATUS_ERROR = 'error';

type ApplicationContextDocumentStatus =
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED
  | typeof APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR;

type ApplicationContextDeletionStatus =
  | typeof APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED
  | typeof APPLICATION_CONTEXT_DELETION_STATUS_ERROR;

export {
  APPLICATION_CONTEXT_DELETION_STATUS_ACCEPTED,
  APPLICATION_CONTEXT_DELETION_STATUS_ERROR,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_ACTIVE,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_DELETED,
  APPLICATION_CONTEXT_DOCUMENT_STATUS_ERROR,
};
export type { ApplicationContextDeletionStatus, ApplicationContextDocumentStatus };
