const DIGEST_CONFIG_KEY_ENABLED = 'digest_enabled';
const DIGEST_CONFIG_KEY_SEND_TIME = 'digest_send_time';
const DIGEST_CONFIG_KEY_SECTIONS = 'digest_sections';
const DIGEST_CONFIG_KEY_LAST_SENT_AT = 'digest_last_sent_at';

const DIGEST_SECTION_CALENDAR = 'calendar';
const DIGEST_SECTION_TASKS = 'tasks';
const DIGEST_SECTION_PACKAGES = 'packages';
const DIGEST_SECTION_FLIGHTS = 'flights';
const DIGEST_SECTION_BILLS = 'bills';
const DIGEST_SECTION_APPOINTMENTS = 'appointments';

const DIGEST_ALL_SECTIONS: string[] = [
  DIGEST_SECTION_CALENDAR,
  DIGEST_SECTION_TASKS,
  DIGEST_SECTION_PACKAGES,
  DIGEST_SECTION_FLIGHTS,
  DIGEST_SECTION_BILLS,
  DIGEST_SECTION_APPOINTMENTS,
];

const DIGEST_BILLS_DUE_DAYS = 7;
const DIGEST_APPOINTMENTS_HOURS = 48;
const DIGEST_CALENDAR_SYNC_DAYS = 7;

export {
  DIGEST_CONFIG_KEY_ENABLED,
  DIGEST_CONFIG_KEY_LAST_SENT_AT,
  DIGEST_CONFIG_KEY_SECTIONS,
  DIGEST_CONFIG_KEY_SEND_TIME,
  DIGEST_SECTION_APPOINTMENTS,
  DIGEST_SECTION_BILLS,
  DIGEST_SECTION_CALENDAR,
  DIGEST_SECTION_FLIGHTS,
  DIGEST_SECTION_PACKAGES,
  DIGEST_SECTION_TASKS,
  DIGEST_ALL_SECTIONS,
  DIGEST_BILLS_DUE_DAYS,
  DIGEST_APPOINTMENTS_HOURS,
  DIGEST_CALENDAR_SYNC_DAYS,
};
