const PROVIDER_GOOGLE_GMAIL = 'google-gmail';
const PROVIDER_MICROSOFT_OUTLOOK = 'microsoft-outlook';
const PROVIDER_FASTMAIL_JMAP = 'fastmail-jmap';
const PROVIDER_YAHOO_MAIL = 'yahoo-mail';
const PROVIDER_CUSTOM_IMAP = 'custom-imap';
const PROVIDER_APPLE_ICLOUD = 'apple-icloud';

const CONNECTION_METHOD_OAUTH2 = 'oauth2';
const CONNECTION_METHOD_IMAP_PASSWORD = 'imap-password';

const CONNECTED_APPLICATION_STATUS_DRAFT = 'draft';
const CONNECTED_APPLICATION_STATUS_CONNECTED = 'connected';
const CONNECTED_APPLICATION_STATUS_ERROR = 'error';

const PROVIDER_SUBSCRIPTION_STATUS_ACTIVE = 'active';
const PROVIDER_SUBSCRIPTION_STATUS_STOPPED = 'stopped';
const PROVIDER_SUBSCRIPTION_STATUS_ERROR = 'error';

const PROCESSED_MESSAGE_STATUS_PROCESSING = 'processing';

const SOURCE_TYPE_EMAIL = 'email';
const PROCESSED_MESSAGE_STATUS_SUMMARIZED = 'summarized';
const PROCESSED_MESSAGE_STATUS_SKIPPED = 'skipped';
const PROCESSED_MESSAGE_STATUS_ERROR = 'error';

const EMAIL_ACTION_TYPE_CALENDAR_ADD_EVENT = 'calendar.add_event';
const EMAIL_ACTION_TYPE_EMAIL_DRAFT_REPLY = 'email.draft_reply';
const EMAIL_ACTION_TYPE_EXTERNAL_OPEN_LINK = 'external.open_link';
const EMAIL_ACTION_TYPE_MANUAL_TODO = 'manual.todo';
const EMAIL_ACTION_TYPE_DELIVERY_TRACK_PACKAGE = 'delivery.track_package';
const EMAIL_ACTION_TYPE_TRAVEL_TRACK_FLIGHT = 'travel.track_flight';
const EMAIL_ACTION_TYPE_FINANCE_PAY_BILL = 'finance.pay_bill';
const EMAIL_ACTION_TYPE_APPOINTMENT_CONFIRM = 'appointment.confirm';

const EMAIL_ACTION_STATUS_PENDING = 'pending';
const EMAIL_ACTION_STATUS_EXECUTING = 'executing';
const EMAIL_ACTION_STATUS_SUCCEEDED = 'succeeded';
const EMAIL_ACTION_STATUS_FAILED = 'failed';
const EMAIL_ACTION_STATUS_EXPIRED = 'expired';
const EMAIL_ACTION_STATUS_CANCELLED = 'cancelled';

const EMAIL_ACTION_RISK_LOW = 'low';
const EMAIL_ACTION_RISK_MEDIUM = 'medium';
const EMAIL_ACTION_RISK_HIGH = 'high';

const EMAIL_ACTION_TRIGGER_EMAIL_CALLBACK = 'email_callback';
const EMAIL_ACTION_TRIGGER_WEB_UI = 'web_ui';
const EMAIL_ACTION_TRIGGER_SYSTEM_EXPIRY = 'system_expiry';
const EMAIL_ACTION_TRIGGER_AUTO_EXECUTE = 'auto_execute';
const EMAIL_ACTION_TRIGGER_SCHEDULED = 'scheduled';

const SUPPORTED_PROVIDER_CONNECTIONS = {
  [PROVIDER_GOOGLE_GMAIL]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_MICROSOFT_OUTLOOK]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_FASTMAIL_JMAP]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_YAHOO_MAIL]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_CUSTOM_IMAP]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_APPLE_ICLOUD]: CONNECTION_METHOD_IMAP_PASSWORD,
} as const;

type ProviderId = keyof typeof SUPPORTED_PROVIDER_CONNECTIONS;
type ConnectionMethod = (typeof SUPPORTED_PROVIDER_CONNECTIONS)[ProviderId];

const PROVIDER_SUPPORTED_CONNECTION_METHODS: Record<ProviderId, ReadonlyArray<ConnectionMethod>> = {
  [PROVIDER_GOOGLE_GMAIL]: [CONNECTION_METHOD_OAUTH2, CONNECTION_METHOD_IMAP_PASSWORD],
  [PROVIDER_MICROSOFT_OUTLOOK]: [CONNECTION_METHOD_OAUTH2, CONNECTION_METHOD_IMAP_PASSWORD],
  [PROVIDER_FASTMAIL_JMAP]: [CONNECTION_METHOD_OAUTH2, CONNECTION_METHOD_IMAP_PASSWORD],
  [PROVIDER_YAHOO_MAIL]: [CONNECTION_METHOD_OAUTH2],
  [PROVIDER_CUSTOM_IMAP]: [CONNECTION_METHOD_OAUTH2, CONNECTION_METHOD_IMAP_PASSWORD],
  [PROVIDER_APPLE_ICLOUD]: [CONNECTION_METHOD_IMAP_PASSWORD],
};

const IMAP_PROVIDERS: ReadonlySet<string> = new Set([
  PROVIDER_YAHOO_MAIL,
  PROVIDER_CUSTOM_IMAP,
  PROVIDER_APPLE_ICLOUD,
]);

type ConnectedAppStatus =
  | typeof CONNECTED_APPLICATION_STATUS_DRAFT
  | typeof CONNECTED_APPLICATION_STATUS_CONNECTED
  | typeof CONNECTED_APPLICATION_STATUS_ERROR;
type ProviderSubscriptionStatus =
  | typeof PROVIDER_SUBSCRIPTION_STATUS_ACTIVE
  | typeof PROVIDER_SUBSCRIPTION_STATUS_STOPPED
  | typeof PROVIDER_SUBSCRIPTION_STATUS_ERROR;
type ProcessedMessageStatus =
  | typeof PROCESSED_MESSAGE_STATUS_PROCESSING
  | typeof PROCESSED_MESSAGE_STATUS_SUMMARIZED
  | typeof PROCESSED_MESSAGE_STATUS_SKIPPED
  | typeof PROCESSED_MESSAGE_STATUS_ERROR;

type EmailActionType =
  | typeof EMAIL_ACTION_TYPE_CALENDAR_ADD_EVENT
  | typeof EMAIL_ACTION_TYPE_EMAIL_DRAFT_REPLY
  | typeof EMAIL_ACTION_TYPE_EXTERNAL_OPEN_LINK
  | typeof EMAIL_ACTION_TYPE_MANUAL_TODO
  | typeof EMAIL_ACTION_TYPE_DELIVERY_TRACK_PACKAGE
  | typeof EMAIL_ACTION_TYPE_TRAVEL_TRACK_FLIGHT
  | typeof EMAIL_ACTION_TYPE_FINANCE_PAY_BILL
  | typeof EMAIL_ACTION_TYPE_APPOINTMENT_CONFIRM;
type EmailActionStatus =
  | typeof EMAIL_ACTION_STATUS_PENDING
  | typeof EMAIL_ACTION_STATUS_EXECUTING
  | typeof EMAIL_ACTION_STATUS_SUCCEEDED
  | typeof EMAIL_ACTION_STATUS_FAILED
  | typeof EMAIL_ACTION_STATUS_EXPIRED
  | typeof EMAIL_ACTION_STATUS_CANCELLED;
type EmailActionRiskLevel = typeof EMAIL_ACTION_RISK_LOW | typeof EMAIL_ACTION_RISK_MEDIUM | typeof EMAIL_ACTION_RISK_HIGH;
type EmailActionExecutionTrigger =
  | typeof EMAIL_ACTION_TRIGGER_EMAIL_CALLBACK
  | typeof EMAIL_ACTION_TRIGGER_WEB_UI
  | typeof EMAIL_ACTION_TRIGGER_SYSTEM_EXPIRY
  | typeof EMAIL_ACTION_TRIGGER_AUTO_EXECUTE
  | typeof EMAIL_ACTION_TRIGGER_SCHEDULED;

type SourceType = typeof SOURCE_TYPE_EMAIL;

export {
  CONNECTED_APPLICATION_STATUS_CONNECTED,
  CONNECTED_APPLICATION_STATUS_DRAFT,
  CONNECTED_APPLICATION_STATUS_ERROR,
  CONNECTION_METHOD_OAUTH2,
  CONNECTION_METHOD_IMAP_PASSWORD,
  PROCESSED_MESSAGE_STATUS_ERROR,
  PROCESSED_MESSAGE_STATUS_PROCESSING,
  PROCESSED_MESSAGE_STATUS_SKIPPED,
  PROCESSED_MESSAGE_STATUS_SUMMARIZED,
  EMAIL_ACTION_RISK_HIGH,
  EMAIL_ACTION_RISK_LOW,
  EMAIL_ACTION_RISK_MEDIUM,
  EMAIL_ACTION_STATUS_CANCELLED,
  EMAIL_ACTION_STATUS_EXECUTING,
  EMAIL_ACTION_STATUS_EXPIRED,
  EMAIL_ACTION_STATUS_FAILED,
  EMAIL_ACTION_STATUS_PENDING,
  EMAIL_ACTION_STATUS_SUCCEEDED,
  EMAIL_ACTION_TRIGGER_AUTO_EXECUTE,
  EMAIL_ACTION_TRIGGER_EMAIL_CALLBACK,
  EMAIL_ACTION_TRIGGER_SCHEDULED,
  EMAIL_ACTION_TRIGGER_SYSTEM_EXPIRY,
  EMAIL_ACTION_TRIGGER_WEB_UI,
  EMAIL_ACTION_TYPE_CALENDAR_ADD_EVENT,
  EMAIL_ACTION_TYPE_EMAIL_DRAFT_REPLY,
  EMAIL_ACTION_TYPE_EXTERNAL_OPEN_LINK,
  EMAIL_ACTION_TYPE_MANUAL_TODO,
  EMAIL_ACTION_TYPE_DELIVERY_TRACK_PACKAGE,
  EMAIL_ACTION_TYPE_TRAVEL_TRACK_FLIGHT,
  EMAIL_ACTION_TYPE_FINANCE_PAY_BILL,
  EMAIL_ACTION_TYPE_APPOINTMENT_CONFIRM,
  IMAP_PROVIDERS,
  PROVIDER_SUPPORTED_CONNECTION_METHODS,
  PROVIDER_APPLE_ICLOUD,
  PROVIDER_CUSTOM_IMAP,
  PROVIDER_FASTMAIL_JMAP,
  PROVIDER_GOOGLE_GMAIL,
  PROVIDER_MICROSOFT_OUTLOOK,
  PROVIDER_YAHOO_MAIL,
  PROVIDER_SUBSCRIPTION_STATUS_ACTIVE,
  SOURCE_TYPE_EMAIL,
  PROVIDER_SUBSCRIPTION_STATUS_ERROR,
  PROVIDER_SUBSCRIPTION_STATUS_STOPPED,
  SUPPORTED_PROVIDER_CONNECTIONS,
};
export type {
  ConnectedAppStatus as ConnectedApplicationStatus,
  ConnectionMethod,
  EmailActionExecutionTrigger,
  EmailActionRiskLevel,
  EmailActionStatus,
  EmailActionType,
  ProcessedMessageStatus,
  ProviderId,
  ProviderSubscriptionStatus,
  SourceType,
};
