export const DURABLE_OBJECT_NAMESPACE_GLOBAL: string = 'global';
export const DURABLE_OBJECT_CRON_TASKS_NAME: string = 'cron-tasks';
export const DURABLE_OBJECT_CRON_TASKS_BASE_URL: string = `https://${DURABLE_OBJECT_CRON_TASKS_NAME}.invalid`;
export const DURABLE_OBJECT_CRON_TASKS_RUN_URL: string = `${DURABLE_OBJECT_CRON_TASKS_BASE_URL}/run`;

export const DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_NAME: string = 'oauth2-token-refreshers';
export const DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_BASE_URL: string = `https://${DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_NAME}.invalid`;
export const DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_EXCHANGE_URL: string = `${DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_BASE_URL}/exchange`;
export const DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_REFRESH_URL: string = `${DURABLE_OBJECT_OAUTH2_TOKEN_REFRESHERS_BASE_URL}/refresh`;
