/* eslint-disable @typescript-eslint/no-explicit-any */

import { GetAnalyticsRoute as OriginalGetAnalyticsRoute } from './user/analytics/GET';
import { GetCurrentUserRoute as OriginalGetCurrentUserRoute } from './user/me/GET';
import { ListApplicationsRoute as OriginalListApplicationsRoute } from './user/applications/GET';
import { CreateApplicationRoute as OriginalCreateApplicationRoute } from './user/application/POST';
import { UpdateApplicationRoute as OriginalUpdateApplicationRoute } from './user/application/PUT';
import { DeleteApplicationRoute as OriginalDeleteApplicationRoute } from './user/application/DELETE';
import { UpdateApplicationContextRoute as OriginalUpdateApplicationContextRoute } from './user/application/context/PUT';
import { DismissApplicationErrorRoute as OriginalDismissApplicationErrorRoute } from './user/application/dismiss-error/POST';
import { DeleteApplicationContextDocumentsRoute as OriginalDeleteApplicationContextDocumentsRoute } from './user/application/context/delete-documents/POST';
import { ListApplicationContextDocumentsRoute as OriginalListApplicationContextDocumentsRoute } from './user/application/context/documents/GET';
import { ListApplicationContextDeletionRunsRoute as OriginalListApplicationContextDeletionRunsRoute } from './user/application/context/deletions/GET';
import { GetApplicationContextDocumentProviderLinkRoute as OriginalGetApplicationContextDocumentProviderLinkRoute } from './user/application/context/document/provider-link/GET';
import { ListContextDocumentAuditLogsRoute as OriginalListContextDocumentAuditLogsRoute } from './user/application/context/document/audit-logs/GET';
import { ListEmailActionsRoute as OriginalListEmailActionsRoute } from './user/actions/GET';
import { ListEmailActionExecutionsRoute as OriginalListEmailActionExecutionsRoute } from './user/actions/executions/GET';
import { ExecuteUserEmailActionRoute as OriginalExecuteUserEmailActionRoute } from './user/actions/execute/POST';
import { SnoozeEmailActionRoute as OriginalSnoozeEmailActionRoute } from './user/actions/snooze/POST';
import { ScheduleEmailActionRoute as OriginalScheduleEmailActionRoute } from './user/actions/schedule/POST';
import { GetApplicationFoldersRoute as OriginalGetApplicationFoldersRoute } from './user/application/folders/GET';
import { UpdateApplicationWatchSettingsRoute as OriginalUpdateApplicationWatchSettingsRoute } from './user/application/watch-settings/PUT';
import { CreateOAuth2AuthorizationRoute as OriginalCreateOAuth2AuthorizationRoute } from './user/application/oauth2/authorize/POST';
import { StartApplicationWatchRoute as OriginalStartApplicationWatchRoute } from './user/application/watch/POST';
import { StopApplicationWatchRoute as OriginalStopApplicationWatchRoute } from './user/application/stop/POST';
import { ListIntegrationsRoute as OriginalListIntegrationsRoute } from './user/application/integrations/GET';
import { CreateIntegrationRoute as OriginalCreateIntegrationRoute } from './user/application/integrations/POST';
import { UpdateIntegrationRoute as OriginalUpdateIntegrationRoute } from './user/application/integrations/PUT';
import { DeleteIntegrationRoute as OriginalDeleteIntegrationRoute } from './user/application/integrations/DELETE';
import { TestIntegrationRoute as OriginalTestIntegrationRoute } from './user/application/integrations/test/POST';
import { ListIntegrationDeliveriesRoute as OriginalListIntegrationDeliveriesRoute } from './user/application/integrations/deliveries/GET';
import { GetApplicationRulesRoute as OriginalGetApplicationRulesRoute } from './user/application/rules/GET';
import { UpdateApplicationRulesRoute as OriginalUpdateApplicationRulesRoute } from './user/application/rules/PUT';
import { SuggestApplicationRuleRoute as OriginalSuggestApplicationRuleRoute } from './user/application/rules/suggest/POST';
import { GetApplicationLabelsRoute as OriginalGetApplicationLabelsRoute } from './user/application/labels/GET';
import { GetDigestConfigRoute as OriginalGetDigestConfigRoute } from './user/application/digest/GET';
import { UpdateDigestConfigRoute as OriginalUpdateDigestConfigRoute } from './user/application/digest/PUT';
import { SendDigestNowRoute as OriginalSendDigestNowRoute } from './user/application/digest/send/POST';
import { OAuth2CallbackRoute as OriginalOAuth2CallbackRoute } from './api/oauth2/callback/GET';
import { GetActionConfirmationRoute as OriginalGetActionConfirmationRoute } from './api/actions/GET';
import { ExecuteActionCallbackRoute as OriginalExecuteActionCallbackRoute } from './api/actions/execute/POST';
import { FastmailWebhookRoute as OriginalFastmailWebhookRoute } from './api/webhooks/fastmail/POST';
import { GmailWebhookRoute as OriginalGmailWebhookRoute } from './api/webhooks/gmail/POST';
import { OutlookWebhookRoute as OriginalOutlookWebhookRoute } from './api/webhooks/outlook/POST';
import { OutlookLifecycleWebhookRoute as OriginalOutlookLifecycleWebhookRoute } from './api/webhooks/outlook/lifecycle/POST';

import { ListBackgroundTaskRunsRoute as OriginalListBackgroundTaskRunsRoute } from './user/processing/task-runs/GET';
import { ListProcessingCalendarEventsRoute as OriginalListProcessingCalendarEventsRoute } from './user/processing/calendar-events/GET';
import { ListProcessedMessagesRoute as OriginalListProcessedMessagesRoute } from './user/processing/messages/GET';
import { RunTaskNowRoute as OriginalRunTaskNowRoute } from './user/processing/run-task/POST';

export const GetAnalyticsRoute: any = OriginalGetAnalyticsRoute;
export const GetCurrentUserRoute: any = OriginalGetCurrentUserRoute;
export const ListApplicationsRoute: any = OriginalListApplicationsRoute;
export const CreateApplicationRoute: any = OriginalCreateApplicationRoute;
export const UpdateApplicationRoute: any = OriginalUpdateApplicationRoute;
export const DeleteApplicationRoute: any = OriginalDeleteApplicationRoute;
export const UpdateApplicationContextRoute: any = OriginalUpdateApplicationContextRoute;
export const DismissApplicationErrorRoute: any = OriginalDismissApplicationErrorRoute;
export const DeleteApplicationContextDocumentsRoute: any = OriginalDeleteApplicationContextDocumentsRoute;
export const ListApplicationContextDocumentsRoute: any = OriginalListApplicationContextDocumentsRoute;
export const ListApplicationContextDeletionRunsRoute: any = OriginalListApplicationContextDeletionRunsRoute;
export const GetApplicationContextDocumentProviderLinkRoute: any = OriginalGetApplicationContextDocumentProviderLinkRoute;
export const ListContextDocumentAuditLogsRoute: any = OriginalListContextDocumentAuditLogsRoute;
export const ListEmailActionsRoute: any = OriginalListEmailActionsRoute;
export const ListEmailActionExecutionsRoute: any = OriginalListEmailActionExecutionsRoute;
export const ExecuteUserEmailActionRoute: any = OriginalExecuteUserEmailActionRoute;
export const SnoozeEmailActionRoute: any = OriginalSnoozeEmailActionRoute;
export const ScheduleEmailActionRoute: any = OriginalScheduleEmailActionRoute;
export const GetApplicationFoldersRoute: any = OriginalGetApplicationFoldersRoute;
export const UpdateApplicationWatchSettingsRoute: any = OriginalUpdateApplicationWatchSettingsRoute;
export const CreateOAuth2AuthorizationRoute: any = OriginalCreateOAuth2AuthorizationRoute;
export const StartApplicationWatchRoute: any = OriginalStartApplicationWatchRoute;
export const StopApplicationWatchRoute: any = OriginalStopApplicationWatchRoute;
export const OAuth2CallbackRoute: any = OriginalOAuth2CallbackRoute;
export const GetActionConfirmationRoute: any = OriginalGetActionConfirmationRoute;
export const ExecuteActionCallbackRoute: any = OriginalExecuteActionCallbackRoute;
export const FastmailWebhookRoute: any = OriginalFastmailWebhookRoute;
export const GmailWebhookRoute: any = OriginalGmailWebhookRoute;
export const OutlookWebhookRoute: any = OriginalOutlookWebhookRoute;
export const OutlookLifecycleWebhookRoute: any = OriginalOutlookLifecycleWebhookRoute;
export const ListIntegrationsRoute: any = OriginalListIntegrationsRoute;
export const CreateIntegrationRoute: any = OriginalCreateIntegrationRoute;
export const UpdateIntegrationRoute: any = OriginalUpdateIntegrationRoute;
export const DeleteIntegrationRoute: any = OriginalDeleteIntegrationRoute;
export const TestIntegrationRoute: any = OriginalTestIntegrationRoute;
export const ListIntegrationDeliveriesRoute: any = OriginalListIntegrationDeliveriesRoute;
export const GetApplicationRulesRoute: any = OriginalGetApplicationRulesRoute;
export const UpdateApplicationRulesRoute: any = OriginalUpdateApplicationRulesRoute;
export const SuggestApplicationRuleRoute: any = OriginalSuggestApplicationRuleRoute;
export const GetApplicationLabelsRoute: any = OriginalGetApplicationLabelsRoute;
export const GetDigestConfigRoute: any = OriginalGetDigestConfigRoute;
export const UpdateDigestConfigRoute: any = OriginalUpdateDigestConfigRoute;
export const SendDigestNowRoute: any = OriginalSendDigestNowRoute;
export const ListBackgroundTaskRunsRoute: any = OriginalListBackgroundTaskRunsRoute;
export const ListProcessingCalendarEventsRoute: any = OriginalListProcessingCalendarEventsRoute;
export const ListProcessedMessagesRoute: any = OriginalListProcessedMessagesRoute;
export const RunTaskNowRoute: any = OriginalRunTaskNowRoute;
